lista = [8, 5, 1, 9, 23, 19, 58, 39 ]
wartosc = input('wprowadz liczbe')
index = input('podaj index')
lista.insert(int(index), int(wartosc))
print(lista)
a = int(input('podaj 1 liczbe'))
b = int(input('podaj 2 liczbe'))
c = int(input('podaj 3 liczbe'))
lista.append(a)
lista.append(b)
lista.append(c)
print(lista)
removal = input("podaj index usuniecia")
lista.pop(int(removal))
print(lista)
lista.reverse()
print(lista)
lista.sort()
print(lista)
